Attempt to include a static JS file in highlight.bundle.js. This fails `gulp bundle` with
```
[20:20:00] Using gulpfile /home/tree/git/antora-ui-khronos/gulpfile.js
[20:20:00] Starting 'bundle'...
[20:20:00] Starting 'clean'...
[20:20:00] Finished 'clean' after 18 ms
[20:20:00] Starting 'lint:css'...
[20:20:00] Starting 'lint:js'...
[20:20:02] Finished 'lint:js' after 1.6 s
[20:20:02] Finished 'lint:css' after 2.37 s
[20:20:02] Starting 'build'...
[20:20:03] gulp-imagemin: Minified 7 images (saved 19.4 kB - 88.1%)
[20:20:03] 'build' errored after 762 ms
[20:20:03] Error: Can't walk dependency graph: Cannot find module './js/vendor/hlsl.js' from '/home/tree/git/antora-ui-khronos/src/js/vendor/highlight.bundle.js'
    required by /home/tree/git/antora-ui-khronos/src/js/vendor/highlight.bundle.js
    at /home/tree/git/antora-ui-khronos/node_modules/resolve/lib/async.js:167:35
    at load (/home/tree/git/antora-ui-khronos/node_modules/resolve/lib/async.js:186:43)
    at onex (/home/tree/git/antora-ui-khronos/node_modules/resolve/lib/async.js:211:17)
    at /home/tree/git/antora-ui-khronos/node_modules/resolve/lib/async.js:24:69
    at FSReqCallback.oncomplete (node:fs:208:21)
    at FSReqCallback.callbackTrampoline (node:internal/async_hooks:130:17)
[20:20:03] 'bundle' errored after 3.15 s
```